return {
  -- "elixir-tools/elixir-tools.nvim",
  -- version = "*",
  -- event = { "BufReadPre", "BufNewFile" },
  -- config = function()
  --   local elixir = require("elixir")
  --   local elixirls = require("elixir.elixirls")
  --
  --   elixir.setup({
  --     credo = {},
  --     elixirls = {
  --       enable = false,
  --       settings = elixirls.settings({
  --         dialyzerEnabled = false,
  --         enableTestLenses = false,
  --       }),
  --       on_attach = function(client, bufnr)
  --         vim.keymap.set("n", "<space>ceo", ":ElixirFromPipe<cr>", { buffer = true, noremap = true })
  --         vim.keymap.set("n", "<space>cep", ":ElixirToPipe<cr>", { buffer = true, noremap = true })
  --         vim.keymap.set("v", "<space>cem", ":ElixirExpandMacro<cr>", { buffer = true, noremap = true })
  --       end,
  --     },
  --   })
  -- end,
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  -- },
}
