theme = "github_dark_dimmed"

[editor]
auto-completion = true
auto-format = true
auto-info = true
auto-save = true
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
scrolloff = 1
undercurl = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
